CRUDNET/Controllers/MantenedorController.cs
using Microsoft.AspNetCore.Mvc;
using test.Models.Datos;
using test.Models;

namespace test.Controllers
{
    public class MantenedorController : Controller
    {

        ContactoDatos _ContactoDatos =new ContactoDatos();

        public IActionResult Listar()
        {
            var oLista = _ContactoDatos.Listar();
            return View(oLista);
           
        }
        public IActionResult Guardar()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Guardar(ContactoModel oContacto)
        {
            if(!ModelState.IsValid)
                return View();

            var rpt= _ContactoDatos.Guardar(oContacto);

            if(rpt)
                return RedirectToAction("Listar");
            return View();
        }

        public IActionResult Editar(int IdContacto)
        {
            var oContacto = _ContactoDatos.Obtener(IdContacto);
            return View(oContacto);
        }
        [HttpPost]
        public IActionResult Editar(ContactoModel oContacto)
        {
            if (!ModelState.IsValid)
                return View();

            var rpt = _ContactoDatos.Editar(oContacto);

            if (rpt)
                return RedirectToAction("Listar");
            return View();
        }

        public IActionResult Eliminar(int IdContacto)
        {
            var oContacto = _ContactoDatos.Obtener(IdContacto);
            return View(oContacto);
        }
        [HttpPost]
        public IActionResult Eliminar(ContactoModel oContacto)
        {
          

            var rpt = _ContactoDatos.Eliminar(oContacto.IdContacto);

            if (rpt)
                return RedirectToAction("Listar");
            return View();
        }

    }
}

CRUDNET/Views/Mantenedor/Editar.cshtml
@model ContactoModel
@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Editar contacto
    </div>
    <div class="card-body">
        <form asp-action="Editar" asp-controller="Mantenedor" method="post">
            <input asp-for="Nombre" type="hidden" class="form-control">

            <div class="mb-3">
                <label class="form-label">Nombre</label>
                <input asp-for="Nombre" type="text" class="form-control">
                <span asp-validation-for="Nombre" class="text-danger"></span>

            </div>
            <div class="mb-3">
                <label class="form-label">Telefono</label>
                <input asp-for="Telefono" type="text" class="form-control">
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="mb-3 ">
                <label class="form-label">Correo</label>
                <input asp-for="Correo" type="text" class="form-control">
                <span asp-validation-for="Correo" class="text-danger"></span>

            </div>
            <button type="submit" class="btn btn-primary">Guardar</button>
            <a asp-action="Listar" asp-controller="Mantenedor" class="btn-warning">Volver a la lista</a>
        </form>
    </div>
</div>

CRUDNET/Views/Mantenedor/Eliminar.cshtml
@model ContactoModel
@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Eliminar</h1>

<div class="card">
    <div class="card-header">
        Editar contacto
    </div>
    <div class="card-body">
        <form asp-action="Eliminar" asp-controller="Mantenedor" method="post">
            <input asp-for="Nombre" type="hidden" class="form-control">

          <div class="alert alert-danger" role="alert">
              ¿Desea eliminar el contacto: @Html.DisplayTextFor(m => m.Nombre)?
          </div>
            <button type="submit" class="btn btn-primary">Eliminar</button>
            <a asp-action="Listar" asp-controller="Mantenedor" class="btn-warning">Volver a la lista</a>
        </form>
    </div>
</div>

CRUDNET/Views/Mantenedor/Guardar.cshtml
@model ContactoModel
@{
    ViewData["Title"] = "Guardar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Crear contacto
    </div>
    <div class="card-body">
        <form asp-action="Guardar" asp-controller="Mantenedor" method="post">
            <div class="mb-3">
                <label  class="form-label">Nombre</label>
                <input asp-for="Nombre" type="text" class="form-control" >
                <span asp-validation-for="Nombre" class="text-danger"></span>
               
            </div>
            <div class="mb-3">
                <label  class="form-label">Telefono</label>
                <input asp-for="Telefono" type="text" class="form-control">
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="mb-3 ">
                <label class="form-label">Correo</label>
                <input asp-for="Correo" type="text" class="form-control">
                <span asp-validation-for="Correo" class="text-danger"></span>
               
            </div>
            <button type="submit" class="btn btn-primary">Guardar</button>
            <a asp-action="Listar" asp-controller="Mantenedor" class="btn-warning">Volver a la lista</a>
        </form>
    </div>
</div>

CRUDNET/Views/Mantenedor/Listar.cshtml
@model List<ContactoModel>
@{
    ViewData["Title"] = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Lista contacto
    </div>
    <div class="card-body">
        <a asp-action="Guardar" asp-contdoller="Mantenedor" class="btn-success">Nuevo contacto</a>
    <hr />
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Telefono</th>
                    <th>Correo</th>
                </tr>
            </thead>
            <tbody>
                @foreach(var item in Model)
                {
                    <tr>    
                        <td>@item.Nombre</td>
                        <td>@item.Telefono</td>
                        <td>@item.Correo</td>
                        <td>  <a asp-action="Editar" asp-contdoller="Mantenedor" class="btn-primary btn-sm" asp-route-IdContacto="@item.IdContacto">Editar</a></td>
                        <td><a asp-action="Eliminar" asp-contdoller="Mantenedor" class="btn-danger btn-sm" asp-route-IdContacto="@item.IdContacto">Eliminar</a></td>
                    </tr>
                }
            </tbody>

        </table>

      
    </div>
</div>